/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_modelType = new Property();
			pAccount_modelType.name = "modelType";
			pAccount_modelType.properUtype = 2;
			pAccount_modelType.properFlags = 4;
			pAccount_modelType.aliasID = 4;
			Int32 Account_modelType_defval;
			Int32.TryParse("0", out Account_modelType_defval);
			pAccount_modelType.defaultVal = Account_modelType_defval;
			pAccountModule.propertys["modelType"] = pAccount_modelType; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_modelType.aliasID] = pAccount_modelType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(modelType / 2).");

			Property pAccount_playerExp = new Property();
			pAccount_playerExp.name = "playerExp";
			pAccount_playerExp.properUtype = 6;
			pAccount_playerExp.properFlags = 32;
			pAccount_playerExp.aliasID = 5;
			Int64 Account_playerExp_defval;
			Int64.TryParse("0", out Account_playerExp_defval);
			pAccount_playerExp.defaultVal = Account_playerExp_defval;
			pAccountModule.propertys["playerExp"] = pAccount_playerExp; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerExp.aliasID] = pAccount_playerExp;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerExp / 6).");

			Property pAccount_playerID = new Property();
			pAccount_playerID.name = "playerID";
			pAccount_playerID.properUtype = 5;
			pAccount_playerID.properFlags = 32;
			pAccount_playerID.aliasID = 6;
			UInt16 Account_playerID_defval;
			UInt16.TryParse("0", out Account_playerID_defval);
			pAccount_playerID.defaultVal = Account_playerID_defval;
			pAccountModule.propertys["playerID"] = pAccount_playerID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerID.aliasID] = pAccount_playerID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerID / 5).");

			Property pAccount_playerLayer = new Property();
			pAccount_playerLayer.name = "playerLayer";
			pAccount_playerLayer.properUtype = 11;
			pAccount_playerLayer.properFlags = 4;
			pAccount_playerLayer.aliasID = 7;
			Int32 Account_playerLayer_defval;
			Int32.TryParse("1", out Account_playerLayer_defval);
			pAccount_playerLayer.defaultVal = Account_playerLayer_defval;
			pAccountModule.propertys["playerLayer"] = pAccount_playerLayer; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerLayer.aliasID] = pAccount_playerLayer;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerLayer / 11).");

			Property pAccount_playerMass = new Property();
			pAccount_playerMass.name = "playerMass";
			pAccount_playerMass.properUtype = 9;
			pAccount_playerMass.properFlags = 4;
			pAccount_playerMass.aliasID = 8;
			Int32 Account_playerMass_defval;
			Int32.TryParse("1", out Account_playerMass_defval);
			pAccount_playerMass.defaultVal = Account_playerMass_defval;
			pAccountModule.propertys["playerMass"] = pAccount_playerMass; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerMass.aliasID] = pAccount_playerMass;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerMass / 9).");

			Property pAccount_playerName = new Property();
			pAccount_playerName.name = "playerName";
			pAccount_playerName.properUtype = 4;
			pAccount_playerName.properFlags = 4;
			pAccount_playerName.aliasID = 9;
			string Account_playerName_defval = "";
			pAccount_playerName.defaultVal = Account_playerName_defval;
			pAccountModule.propertys["playerName"] = pAccount_playerName; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerName.aliasID] = pAccount_playerName;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerName / 4).");

			Property pAccount_playerNameBase = new Property();
			pAccount_playerNameBase.name = "playerNameBase";
			pAccount_playerNameBase.properUtype = 3;
			pAccount_playerNameBase.properFlags = 32;
			pAccount_playerNameBase.aliasID = 10;
			string Account_playerNameBase_defval = "";
			pAccount_playerNameBase.defaultVal = Account_playerNameBase_defval;
			pAccountModule.propertys["playerNameBase"] = pAccount_playerNameBase; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerNameBase.aliasID] = pAccount_playerNameBase;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerNameBase / 3).");

			Property pAccount_playerScale = new Property();
			pAccount_playerScale.name = "playerScale";
			pAccount_playerScale.properUtype = 8;
			pAccount_playerScale.properFlags = 4;
			pAccount_playerScale.aliasID = 11;
			float Account_playerScale_defval;
			float.TryParse("1.0", out Account_playerScale_defval);
			pAccount_playerScale.defaultVal = Account_playerScale_defval;
			pAccountModule.propertys["playerScale"] = pAccount_playerScale; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerScale.aliasID] = pAccount_playerScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerScale / 8).");

			Property pAccount_playerSpeed = new Property();
			pAccount_playerSpeed.name = "playerSpeed";
			pAccount_playerSpeed.properUtype = 10;
			pAccount_playerSpeed.properFlags = 4;
			pAccount_playerSpeed.aliasID = 12;
			float Account_playerSpeed_defval;
			float.TryParse("8.0", out Account_playerSpeed_defval);
			pAccount_playerSpeed.defaultVal = Account_playerSpeed_defval;
			pAccountModule.propertys["playerSpeed"] = pAccount_playerSpeed; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerSpeed.aliasID] = pAccount_playerSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerSpeed / 10).");

			Property pAccount_playerState = new Property();
			pAccount_playerState.name = "playerState";
			pAccount_playerState.properUtype = 7;
			pAccount_playerState.properFlags = 4;
			pAccount_playerState.aliasID = 13;
			Int32 Account_playerState_defval;
			Int32.TryParse("1", out Account_playerState_defval);
			pAccount_playerState.defaultVal = Account_playerState_defval;
			pAccountModule.propertys["playerState"] = pAccount_playerState; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerState.aliasID] = pAccount_playerState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerState / 7).");

			List<DATATYPE_BASE> pAccount_playerAlive_args = new List<DATATYPE_BASE>();
			pAccount_playerAlive_args.Add(EntityDef.id2datatypes[20]);

			Method pAccount_playerAlive = new Method();
			pAccount_playerAlive.name = "playerAlive";
			pAccount_playerAlive.methodUtype = 12;
			pAccount_playerAlive.aliasID = 1;
			pAccount_playerAlive.args = pAccount_playerAlive_args;

			pAccountModule.methods["playerAlive"] = pAccount_playerAlive; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_playerAlive.aliasID] = pAccount_playerAlive;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerAlive / 12).");

			List<DATATYPE_BASE> pAccount_playerDead_args = new List<DATATYPE_BASE>();
			pAccount_playerDead_args.Add(EntityDef.id2datatypes[20]);

			Method pAccount_playerDead = new Method();
			pAccount_playerDead.name = "playerDead";
			pAccount_playerDead.methodUtype = 11;
			pAccount_playerDead.aliasID = 2;
			pAccount_playerDead.args = pAccount_playerDead_args;

			pAccountModule.methods["playerDead"] = pAccount_playerDead; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_playerDead.aliasID] = pAccount_playerDead;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerDead / 11).");

			List<DATATYPE_BASE> pAccount_playerGameOver_args = new List<DATATYPE_BASE>();

			Method pAccount_playerGameOver = new Method();
			pAccount_playerGameOver.name = "playerGameOver";
			pAccount_playerGameOver.methodUtype = 13;
			pAccount_playerGameOver.aliasID = 3;
			pAccount_playerGameOver.args = pAccount_playerGameOver_args;

			pAccountModule.methods["playerGameOver"] = pAccount_playerGameOver; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_playerGameOver.aliasID] = pAccount_playerGameOver;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerGameOver / 13).");

			List<DATATYPE_BASE> pAccount_playBattleGame_args = new List<DATATYPE_BASE>();

			Method pAccount_playBattleGame = new Method();
			pAccount_playBattleGame.name = "playBattleGame";
			pAccount_playBattleGame.methodUtype = 7;
			pAccount_playBattleGame.aliasID = -1;
			pAccount_playBattleGame.args = pAccount_playBattleGame_args;

			pAccountModule.methods["playBattleGame"] = pAccount_playBattleGame; 
			pAccountModule.base_methods["playBattleGame"] = pAccount_playBattleGame;

			pAccountModule.idbase_methods[pAccount_playBattleGame.methodUtype] = pAccount_playBattleGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playBattleGame / 7).");

			List<DATATYPE_BASE> pAccount_playIndiviGame_args = new List<DATATYPE_BASE>();

			Method pAccount_playIndiviGame = new Method();
			pAccount_playIndiviGame.name = "playIndiviGame";
			pAccount_playIndiviGame.methodUtype = 6;
			pAccount_playIndiviGame.aliasID = -1;
			pAccount_playIndiviGame.args = pAccount_playIndiviGame_args;

			pAccountModule.methods["playIndiviGame"] = pAccount_playIndiviGame; 
			pAccountModule.base_methods["playIndiviGame"] = pAccount_playIndiviGame;

			pAccountModule.idbase_methods[pAccount_playIndiviGame.methodUtype] = pAccount_playIndiviGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playIndiviGame / 6).");

			List<DATATYPE_BASE> pAccount_playTeamGame_args = new List<DATATYPE_BASE>();

			Method pAccount_playTeamGame = new Method();
			pAccount_playTeamGame.name = "playTeamGame";
			pAccount_playTeamGame.methodUtype = 8;
			pAccount_playTeamGame.aliasID = -1;
			pAccount_playTeamGame.args = pAccount_playTeamGame_args;

			pAccountModule.methods["playTeamGame"] = pAccount_playTeamGame; 
			pAccountModule.base_methods["playTeamGame"] = pAccount_playTeamGame;

			pAccountModule.idbase_methods[pAccount_playTeamGame.methodUtype] = pAccount_playTeamGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playTeamGame / 8).");

			List<DATATYPE_BASE> pAccount_playerLeaveRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_playerLeaveRoom = new Method();
			pAccount_playerLeaveRoom.name = "playerLeaveRoom";
			pAccount_playerLeaveRoom.methodUtype = 10;
			pAccount_playerLeaveRoom.aliasID = -1;
			pAccount_playerLeaveRoom.args = pAccount_playerLeaveRoom_args;

			pAccountModule.methods["playerLeaveRoom"] = pAccount_playerLeaveRoom; 
			pAccountModule.base_methods["playerLeaveRoom"] = pAccount_playerLeaveRoom;

			pAccountModule.idbase_methods[pAccount_playerLeaveRoom.methodUtype] = pAccount_playerLeaveRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerLeaveRoom / 10).");

			List<DATATYPE_BASE> pAccount_updatePlayerExp_args = new List<DATATYPE_BASE>();
			pAccount_updatePlayerExp_args.Add(EntityDef.id2datatypes[3]);

			Method pAccount_updatePlayerExp = new Method();
			pAccount_updatePlayerExp.name = "updatePlayerExp";
			pAccount_updatePlayerExp.methodUtype = 4;
			pAccount_updatePlayerExp.aliasID = -1;
			pAccount_updatePlayerExp.args = pAccount_updatePlayerExp_args;

			pAccountModule.methods["updatePlayerExp"] = pAccount_updatePlayerExp; 
			pAccountModule.base_methods["updatePlayerExp"] = pAccount_updatePlayerExp;

			pAccountModule.idbase_methods[pAccount_updatePlayerExp.methodUtype] = pAccount_updatePlayerExp;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(updatePlayerExp / 4).");

			List<DATATYPE_BASE> pAccount_updatePlayerName_args = new List<DATATYPE_BASE>();
			pAccount_updatePlayerName_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_updatePlayerName = new Method();
			pAccount_updatePlayerName.name = "updatePlayerName";
			pAccount_updatePlayerName.methodUtype = 3;
			pAccount_updatePlayerName.aliasID = -1;
			pAccount_updatePlayerName.args = pAccount_updatePlayerName_args;

			pAccountModule.methods["updatePlayerName"] = pAccount_updatePlayerName; 
			pAccountModule.base_methods["updatePlayerName"] = pAccount_updatePlayerName;

			pAccountModule.idbase_methods[pAccount_updatePlayerName.methodUtype] = pAccount_updatePlayerName;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(updatePlayerName / 3).");

			ScriptModule pFoodModule = new ScriptModule("Food");
			EntityDef.moduledefs["Food"] = pFoodModule;
			EntityDef.idmoduledefs[4] = pFoodModule;

			Property pFood_position = new Property();
			pFood_position.name = "position";
			pFood_position.properUtype = 40000;
			pFood_position.properFlags = 4;
			pFood_position.aliasID = 1;
			Vector3 Food_position_defval = new Vector3();
			pFood_position.defaultVal = Food_position_defval;
			pFoodModule.propertys["position"] = pFood_position; 

			pFoodModule.usePropertyDescrAlias = true;
			pFoodModule.idpropertys[(UInt16)pFood_position.aliasID] = pFood_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Food), property(position / 40000).");

			Property pFood_direction = new Property();
			pFood_direction.name = "direction";
			pFood_direction.properUtype = 40001;
			pFood_direction.properFlags = 4;
			pFood_direction.aliasID = 2;
			Vector3 Food_direction_defval = new Vector3();
			pFood_direction.defaultVal = Food_direction_defval;
			pFoodModule.propertys["direction"] = pFood_direction; 

			pFoodModule.usePropertyDescrAlias = true;
			pFoodModule.idpropertys[(UInt16)pFood_direction.aliasID] = pFood_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Food), property(direction / 40001).");

			Property pFood_spaceID = new Property();
			pFood_spaceID.name = "spaceID";
			pFood_spaceID.properUtype = 40002;
			pFood_spaceID.properFlags = 16;
			pFood_spaceID.aliasID = 3;
			UInt32 Food_spaceID_defval;
			UInt32.TryParse("", out Food_spaceID_defval);
			pFood_spaceID.defaultVal = Food_spaceID_defval;
			pFoodModule.propertys["spaceID"] = pFood_spaceID; 

			pFoodModule.usePropertyDescrAlias = true;
			pFoodModule.idpropertys[(UInt16)pFood_spaceID.aliasID] = pFood_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Food), property(spaceID / 40002).");

			Property pFood_foodID = new Property();
			pFood_foodID.name = "foodID";
			pFood_foodID.properUtype = 17;
			pFood_foodID.properFlags = 4;
			pFood_foodID.aliasID = 4;
			UInt64 Food_foodID_defval;
			UInt64.TryParse("", out Food_foodID_defval);
			pFood_foodID.defaultVal = Food_foodID_defval;
			pFoodModule.propertys["foodID"] = pFood_foodID; 

			pFoodModule.usePropertyDescrAlias = true;
			pFoodModule.idpropertys[(UInt16)pFood_foodID.aliasID] = pFood_foodID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Food), property(foodID / 17).");

			Property pFood_modelType = new Property();
			pFood_modelType.name = "modelType";
			pFood_modelType.properUtype = 16;
			pFood_modelType.properFlags = 4;
			pFood_modelType.aliasID = 5;
			Int32 Food_modelType_defval;
			Int32.TryParse("0", out Food_modelType_defval);
			pFood_modelType.defaultVal = Food_modelType_defval;
			pFoodModule.propertys["modelType"] = pFood_modelType; 

			pFoodModule.usePropertyDescrAlias = true;
			pFoodModule.idpropertys[(UInt16)pFood_modelType.aliasID] = pFood_modelType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Food), property(modelType / 16).");

			pFoodModule.useMethodDescrAlias = true;
			ScriptModule pSmashModule = new ScriptModule("Smash");
			EntityDef.moduledefs["Smash"] = pSmashModule;
			EntityDef.idmoduledefs[5] = pSmashModule;

			Property pSmash_position = new Property();
			pSmash_position.name = "position";
			pSmash_position.properUtype = 40000;
			pSmash_position.properFlags = 4;
			pSmash_position.aliasID = 1;
			Vector3 Smash_position_defval = new Vector3();
			pSmash_position.defaultVal = Smash_position_defval;
			pSmashModule.propertys["position"] = pSmash_position; 

			pSmashModule.usePropertyDescrAlias = true;
			pSmashModule.idpropertys[(UInt16)pSmash_position.aliasID] = pSmash_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Smash), property(position / 40000).");

			Property pSmash_direction = new Property();
			pSmash_direction.name = "direction";
			pSmash_direction.properUtype = 40001;
			pSmash_direction.properFlags = 4;
			pSmash_direction.aliasID = 2;
			Vector3 Smash_direction_defval = new Vector3();
			pSmash_direction.defaultVal = Smash_direction_defval;
			pSmashModule.propertys["direction"] = pSmash_direction; 

			pSmashModule.usePropertyDescrAlias = true;
			pSmashModule.idpropertys[(UInt16)pSmash_direction.aliasID] = pSmash_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Smash), property(direction / 40001).");

			Property pSmash_spaceID = new Property();
			pSmash_spaceID.name = "spaceID";
			pSmash_spaceID.properUtype = 40002;
			pSmash_spaceID.properFlags = 16;
			pSmash_spaceID.aliasID = 3;
			UInt32 Smash_spaceID_defval;
			UInt32.TryParse("", out Smash_spaceID_defval);
			pSmash_spaceID.defaultVal = Smash_spaceID_defval;
			pSmashModule.propertys["spaceID"] = pSmash_spaceID; 

			pSmashModule.usePropertyDescrAlias = true;
			pSmashModule.idpropertys[(UInt16)pSmash_spaceID.aliasID] = pSmash_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Smash), property(spaceID / 40002).");

			Property pSmash_modelType = new Property();
			pSmash_modelType.name = "modelType";
			pSmash_modelType.properUtype = 20;
			pSmash_modelType.properFlags = 4;
			pSmash_modelType.aliasID = 4;
			Int32 Smash_modelType_defval;
			Int32.TryParse("0", out Smash_modelType_defval);
			pSmash_modelType.defaultVal = Smash_modelType_defval;
			pSmashModule.propertys["modelType"] = pSmash_modelType; 

			pSmashModule.usePropertyDescrAlias = true;
			pSmashModule.idpropertys[(UInt16)pSmash_modelType.aliasID] = pSmash_modelType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Smash), property(modelType / 20).");

			Property pSmash_smashID = new Property();
			pSmash_smashID.name = "smashID";
			pSmash_smashID.properUtype = 21;
			pSmash_smashID.properFlags = 4;
			pSmash_smashID.aliasID = 5;
			UInt64 Smash_smashID_defval;
			UInt64.TryParse("0", out Smash_smashID_defval);
			pSmash_smashID.defaultVal = Smash_smashID_defval;
			pSmashModule.propertys["smashID"] = pSmash_smashID; 

			pSmashModule.usePropertyDescrAlias = true;
			pSmashModule.idpropertys[(UInt16)pSmash_smashID.aliasID] = pSmash_smashID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Smash), property(smashID / 21).");

			pSmashModule.useMethodDescrAlias = true;
		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "UINT8";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "UINT64";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "UINT32";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "INT32";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "VECTOR3";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ENTITYLIST";
				DATATYPE_ENTITYLIST datatype = new DATATYPE_ENTITYLIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}